### PR TITLE
Handle publishing to next year

### PR DESCRIPTION
**Pull request by FabienDeshayes**
Tried to publish something in January 2018 and it failed. This detects if the current month is December, and will increment the year to look for January <year + 1> in the agenda.

### CODE REVIEW

**Comment by hermesdj** [comment]
I already fixed this, I will check if I have commited it on the repository

**Comment by FabienDeshayes** [comment]
Want me to close this? I haven't seen your fix - maybe it hasn't been commited yet.

**Comment by hermesdj** [comment]
I did it differently. If you add one month to the date using moment, and it is december, and you format the year, it gives you the next year automatically !

**Comment by FabienDeshayes** [comment]
That sounds even better, thanks!

**Pull request closed without merging**
